# Generated by Django 5.0.4 on 2024-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100)),
                ('main_color', models.CharField(max_length=7)),
                ('send_message_color', models.CharField(max_length=7)),
                ('received_message_color', models.CharField(max_length=7)),
                ('background_color', models.CharField(max_length=7)),
                ('send_message_text_color', models.CharField(max_length=7)),
                ('received_message_text_color', models.CharField(max_length=7)),
                ('assistant_image', models.ImageField(blank=True, null=True, upload_to='assistant_images/')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatar_images/')),
                ('send_icon', models.ImageField(blank=True, null=True, upload_to='send_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
