# Generated by Django 5.0.4 on 2024-07-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='background_color',
            new_name='backgroundColor',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='main_color',
            new_name='mainColor',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='received_message_text_color',
            new_name='receivedMessageColor',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='received_message_color',
            new_name='receivedMessageTextColor',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='send_message_color',
            new_name='sendMessageColor',
        ),
        migrations.RenameField(
            model_name='chatbotsettings',
            old_name='send_message_text_color',
            new_name='sendMessageTextColor',
        ),
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='assistant_image',
        ),
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='avatar_image',
        ),
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='bot_name',
        ),
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='send_icon',
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='assistantAvatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='assistantImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='launcherIcon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='sendIcon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
