# Generated by Django 5.0.4 on 2024-07-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_background_color_chatbotsettings_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_color', models.CharField(max_length=7)),
                ('send_message_color', models.CharField(max_length=7)),
                ('received_message_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_color', models.CharField(max_length=7)),
                ('send_message_text_color', models.CharField(max_length=7)),
                ('received_message_text_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatbotSettings',
        ),
    ]
