# Generated by Django 5.0.4 on 2024-07-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatbotsetting_delete_chatbotsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interaction',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='ChatbotSetting',
        ),
    ]
